{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "carsome-app.fullname" . }}-service
  labels:
    {{- include "carsome-app.labels" . | nindent 4 }}
    {{- include "carsome-app.appLabels" (merge (dict "docType" "service") .) | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.ports }}
    {{- with .Values.service.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.appContainerPort }}
      protocol: TCP
      name: http
  {{- end }} 
  selector:
    {{- include "carsome-app.selectorLabels" . | nindent 4 }}
    {{- include "carsome-app.appLabels" . | nindent 4 }}
{{- end -}}

